INSERT INTO AIRPORT (ID, CITY, CODE, AIRPORTNAME) VALUES (1, 'Rønne', '1124', 'Bornholms Lufthavn');
INSERT INTO AIRPORT (ID, CITY, CODE, AIRPORTNAME) VALUES (2, 'København', '1125', 'Københavns lufthavn');
INSERT INTO AIRPORT (ID, CITY, CODE, AIRPORTNAME) VALUES (3, 'Roskilde', '1126', 'Roskilde lufthavn');
INSERT INTO AIRPORT (ID, CITY, CODE, AIRPORTNAME) VALUES (4, 'Randers', '1127', 'Randers flyplads');
INSERT INTO AIRPORT (ID, CITY, CODE, AIRPORTNAME) VALUES (5, 'Billund', '1128', 'Billund Airport');
