INSERT INTO FLY (ID,SEATS) VALUES (1,1);
INSERT INTO FLY (ID,SEATS) VALUES (2,2);
INSERT INTO FLY (ID,SEATS) VALUES (3,3);
INSERT INTO FLY (ID,SEATS) VALUES (4,4);
INSERT INTO FLY (ID,SEATS) VALUES (5,5);
