INSERT INTO FLY (ID,SEATS,AIRLINE_ID) VALUES (1,1,1);
INSERT INTO FLY (ID,SEATS,AIRLINE_ID) VALUES (2,2,1);
INSERT INTO FLY (ID,SEATS,AIRLINE_ID) VALUES (3,3,1);
INSERT INTO FLY (ID,SEATS,AIRLINE_ID) VALUES (4,4,1);
INSERT INTO FLY (ID,SEATS,AIRLINE_ID) VALUES (5,5,1);
